# origin Travis CI form https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode7.3
rvm:
- 2.1.2

env:
  matrix:
    - UNITY_VERSION=beta
    - UNITY_VERSION=last
    - UNITY_VERSION=5.3
    - UNITY_VERSION=5.2
    - UNITY_VERSION=5.1
    - UNITY_VERSION=5.0

before_install:
- chmod -R +x ./Scripts
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
